server:
  port: 8443
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore.p12
    key-alias: smap
    key-store-password: 789512357
logging:
  level:
    org:
      springframework:
        security: DEBUG
security:
  require-ssl: true
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nomina?serverTimezone=UTC
    username: admin
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  jackson:
    serialization:
      fail-on-empty-beans: false
  servlet: 
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
      enabled: true
  mail:
    username: _
    password: _
    properties:
      mail:
        smtp:
          port: 25
          auth: true
          starttls.enable: true
          starttls.required: true
file:
  upload-dir: C:\Documentos\
  
